# Generated by Django 3.1.4 on 2021-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='solution',
            field=models.BooleanField(default=False),
        ),
    ]
