# Generated by Django 3.1.4 on 2021-01-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='coment',
            new_name='comment',
        ),
    ]
